// ==========================================
// 🧠 AI BRAIN - CENTRAL EXPORT HUB (BARREL FILE)
// ==========================================

// 1. Core Database
import { KNOWLEDGE_BASE } from './knowledge';

// 2. UI Suggestions & Greetings
import {
    SUGGESTED_QUESTIONS,
    SUGGESTED_QUESTIONS_EN,
    GREETINGS,
    GREETINGS_EN,
    SMART_GREETINGS,
    SMART_GREETINGS_EN,
} from './greetings';

// 3. Fallbacks, Rules & Blacklists (+ situational greetings)
import {
    REJECTION_RESPONSES,
    REJECTION_RESPONSES_EN,
    REPEAT_RESPONSES,
    REPEAT_RESPONSES_EN,
    API_FALLBACK_RESPONSES,
    API_FALLBACK_RESPONSES_EN,
    GREETINGS_FORMAL,
    GREETINGS_FORMAL_EN,
    GREETINGS_CASUAL,
    GREETINGS_CASUAL_EN,
    STATUS_HOW_ARE_YOU,
    STATUS_HOW_ARE_YOU_EN,
    STATUS_WHATS_UP,
    STATUS_WHATS_UP_EN,
    OUT_OF_SCOPE_KEYWORDS,
    DESIGN_DICTIONARY_WHITELIST,
    isDesignRelated,
} from './config';

// 4. Combined "Elite" Conversation Engine (intents, profile, NLP, helpers)
import {
    superClean,
    matchesKeyword,
    processKhmerNLP,
    CORRECTION_PATTERNS_EN,
    CORRECTION_PATTERNS_KH,
    UNCERTAIN_PATTERNS_EN,
    UNCERTAIN_PATTERNS_KH,
    CONTINUATION_PATTERNS_EN,
    CONTINUATION_PATTERNS_KH,
    CAPABILITY_PATTERNS_EN,
    CAPABILITY_PATTERNS_KH,
    CAPABILITY_ANSWER_KH,
    CAPABILITY_ANSWER_EN,
    isAffirmative,
    isNegative,
    extractOfferedTopic,
    NO_PIVOTS_KH,
    NO_PIVOTS_EN,
    detectSocialIntent,
    detectGreetingType,
    isHowAreYou,
    isWhatsUp,
    extractProfileSignals,
    readUserProfile,
    updateUserProfile,
    clearUserProfile,
    buildProfileContext,
    parseMultiChoiceQuestion,
    isShortGibberish,
    RETRY_CHIP_EN,
    RETRY_CHIP_KH,
    RETRY_CHIP_LABELS,
    OFFLINE_FALLBACK_CHIPS_EN,
    OFFLINE_FALLBACK_CHIPS_KH,
    SHORT_RETURN_GREETINGS,
    SHORT_RETURN_GREETINGS_EN,
    SHORT_INPUT_REJECTIONS,
    SHORT_INPUT_REJECTIONS_EN,
    GUIDANCE_MENU_KH,
    GUIDANCE_MENU_EN,
    GUIDANCE_CHIPS_KH,
    GUIDANCE_CHIPS_EN,
} from './conversation';

export {
    KNOWLEDGE_BASE,
    SUGGESTED_QUESTIONS,
    SUGGESTED_QUESTIONS_EN,
    GREETINGS,
    GREETINGS_EN,
    SMART_GREETINGS,
    SMART_GREETINGS_EN,
    REJECTION_RESPONSES,
    REJECTION_RESPONSES_EN,
    REPEAT_RESPONSES,
    REPEAT_RESPONSES_EN,
    API_FALLBACK_RESPONSES,
    API_FALLBACK_RESPONSES_EN,
    GREETINGS_FORMAL,
    GREETINGS_FORMAL_EN,
    GREETINGS_CASUAL,
    GREETINGS_CASUAL_EN,
    STATUS_HOW_ARE_YOU,
    STATUS_HOW_ARE_YOU_EN,
    STATUS_WHATS_UP,
    STATUS_WHATS_UP_EN,
    OUT_OF_SCOPE_KEYWORDS,
    DESIGN_DICTIONARY_WHITELIST,
    isDesignRelated,
    // Conversation engine
    superClean,
    matchesKeyword,
    processKhmerNLP,
    CORRECTION_PATTERNS_EN,
    CORRECTION_PATTERNS_KH,
    UNCERTAIN_PATTERNS_EN,
    UNCERTAIN_PATTERNS_KH,
    CONTINUATION_PATTERNS_EN,
    CONTINUATION_PATTERNS_KH,
    CAPABILITY_PATTERNS_EN,
    CAPABILITY_PATTERNS_KH,
    CAPABILITY_ANSWER_KH,
    CAPABILITY_ANSWER_EN,
    isAffirmative,
    isNegative,
    extractOfferedTopic,
    NO_PIVOTS_KH,
    NO_PIVOTS_EN,
    detectSocialIntent,
    detectGreetingType,
    isHowAreYou,
    isWhatsUp,
    extractProfileSignals,
    readUserProfile,
    updateUserProfile,
    clearUserProfile,
    buildProfileContext,
    parseMultiChoiceQuestion,
    isShortGibberish,
    RETRY_CHIP_EN,
    RETRY_CHIP_KH,
    RETRY_CHIP_LABELS,
    OFFLINE_FALLBACK_CHIPS_EN,
    OFFLINE_FALLBACK_CHIPS_KH,
    SHORT_RETURN_GREETINGS,
    SHORT_RETURN_GREETINGS_EN,
    SHORT_INPUT_REJECTIONS,
    SHORT_INPUT_REJECTIONS_EN,
    GUIDANCE_MENU_KH,
    GUIDANCE_MENU_EN,
    GUIDANCE_CHIPS_KH,
    GUIDANCE_CHIPS_EN,
};
